spring.application.name=SpringEduManager

# Configuración de la conexión a MySQL (Puerto estándar 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/edumanager_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=U6q3t5q7n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Crear automáticamente las tablas según nuestras clases Java
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola de IntelliJ
spring.jpa.show-sql=true
